//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.22 at 02:08:56 AM CET 
//


package org.junit.tools.generator.model.tml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssertionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssertionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IS_NULL"/>
 *     &lt;enumeration value="NOT_NULL"/>
 *     &lt;enumeration value="EQUALS"/>
 *     &lt;enumeration value="NOT_EQUALS"/>
 *     &lt;enumeration value="IS_TRUE"/>
 *     &lt;enumeration value="IS_FALSE"/>
 *     &lt;enumeration value="CREATER_THAN"/>
 *     &lt;enumeration value="LOWER_THAN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AssertionType")
@XmlEnum
public enum AssertionType {

    IS_NULL,
    NOT_NULL,
    EQUALS,
    NOT_EQUALS,
    IS_TRUE,
    IS_FALSE,
    CREATER_THAN,
    LOWER_THAN;

    public String value() {
        return name();
    }

    public static AssertionType fromValue(String v) {
        return valueOf(v);
    }

}
