//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.23 at 09:36:22 AM CET 
//


package org.junit.tools.reports.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Report complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Report">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isTestAvailable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="isTestNecessary" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="coveredWith" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="testPrio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isNew" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="onlyNullchecks" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="numberOfIfStatements" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="checkAgain" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Report", propOrder = {
    "id",
    "isTestAvailable",
    "isTestNecessary",
    "coveredWith",
    "date",
    "testPrio",
    "isNew",
    "onlyNullchecks",
    "numberOfIfStatements",
    "checkAgain"
})
public class Report {

    @XmlElement(required = true)
    protected String id;
    protected boolean isTestAvailable;
    protected boolean isTestNecessary;
    @XmlElement(required = true)
    protected String coveredWith;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(required = true)
    protected String testPrio;
    protected boolean isNew;
    protected boolean onlyNullchecks;
    protected int numberOfIfStatements;
    protected boolean checkAgain;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isTestAvailable property.
     * 
     */
    public boolean isIsTestAvailable() {
        return isTestAvailable;
    }

    /**
     * Sets the value of the isTestAvailable property.
     * 
     */
    public void setIsTestAvailable(boolean value) {
        this.isTestAvailable = value;
    }

    /**
     * Gets the value of the isTestNecessary property.
     * 
     */
    public boolean isIsTestNecessary() {
        return isTestNecessary;
    }

    /**
     * Sets the value of the isTestNecessary property.
     * 
     */
    public void setIsTestNecessary(boolean value) {
        this.isTestNecessary = value;
    }

    /**
     * Gets the value of the coveredWith property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoveredWith() {
        return coveredWith;
    }

    /**
     * Sets the value of the coveredWith property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoveredWith(String value) {
        this.coveredWith = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the testPrio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestPrio() {
        return testPrio;
    }

    /**
     * Sets the value of the testPrio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestPrio(String value) {
        this.testPrio = value;
    }

    /**
     * Gets the value of the isNew property.
     * 
     */
    public boolean isIsNew() {
        return isNew;
    }

    /**
     * Sets the value of the isNew property.
     * 
     */
    public void setIsNew(boolean value) {
        this.isNew = value;
    }

    /**
     * Gets the value of the onlyNullchecks property.
     * 
     */
    public boolean isOnlyNullchecks() {
        return onlyNullchecks;
    }

    /**
     * Sets the value of the onlyNullchecks property.
     * 
     */
    public void setOnlyNullchecks(boolean value) {
        this.onlyNullchecks = value;
    }

    /**
     * Gets the value of the numberOfIfStatements property.
     * 
     */
    public int getNumberOfIfStatements() {
        return numberOfIfStatements;
    }

    /**
     * Sets the value of the numberOfIfStatements property.
     * 
     */
    public void setNumberOfIfStatements(int value) {
        this.numberOfIfStatements = value;
    }

    /**
     * Gets the value of the checkAgain property.
     * 
     */
    public boolean isCheckAgain() {
        return checkAgain;
    }

    /**
     * Sets the value of the checkAgain property.
     * 
     */
    public void setCheckAgain(boolean value) {
        this.checkAgain = value;
    }

}
